---
extra_javascript:
  - jquery.min.js
  - jquery.fancybox.min.js
  - zversions.js
extra_css:
  - extra.css
  - jquery.fancybox.min.css
markdown_extensions:
- meta
- admonition
- footnotes
- meta
- attr_list
- codehilite: {guess_lang: true}
- toc: {permalink: true}
- pymdownx.betterem: {smart_enable: all}
- pymdownx.caret
- pymdownx.critic
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist: {custom_checkbox: true}
- pymdownx.tabbed
- pymdownx.tilde
nav:
- Getting Started:
  - Zerynth in 5 minutes: gettingstarted/index.md
  - ZM1 Development Board: gettingstarted/ZM1-DB.md
  - ZM1 Evaluation Board: gettingstarted/ZM1-EVA.md
  - 4ZeroBox: gettingstarted/4ZeroBox.md
  - Visual Studio Code: gettingstarted/vscode.md
- Tutorials:
  - tutorials/index.md
  - tutorials/cli.md
  - tutorials/digicomm.md
  - tutorials/multithreaded.md
  - tutorials/rs485.md
  - tutorials/eth.md
  - tutorials/wifi.md
  - tutorials/mqtt.md
  - tutorials/https.md
- Zerynth Cloud:
  - Introduction: zCloud/index.md
  - zDeviceManager: zCloud/zdm_intro.md
  - zStorage: zCloud/zstorage_intro.md
  - zDashboard: zCloud/zdashboard_intro.md
  - {Tutorials: zCloud/intro.md}
  - Connect to zCloud: zCloud/connect.md
  # - Store and Visualize data: zCloud/store_visualize.md
  # - Make Simple Powerful Dashboards: zCloud/dashboard.md
  - Over the Air Updates: zCloud/FOTA.md
- Hardware:
  - {Hardware Platforms: hardware/index.md}
  - hardware/ZM1-Development-Board.md
  - hardware/4ZeroBox.md
  - hardware/EXP-SER.md
  - hardware/EXP-RELAY.md
  - hardware/EXP-IO.md
  - hardware/EXP-PROTO.md
- Technical Reference:
    - {Introduction: reference/index.md}
    - Zerynth SDK:
      - Zerynth OS: 
        - reference/os/index.md
        - reference/os/basics.md
        - reference/os/seqmap.md
        - reference/os/pinmap.md
        - reference/os/clang.md
        - reference/os/os.md
      - Development Environment: reference/vscode/index.md
      - Boards and Expansions:
        - reference/libs/expansions/index.md
        - reference/bsp/4zerobox_v9.md
        - reference/bsp/zm1_db.md
        - reference/libs/expansions/exp-io.md
        - reference/libs/expansions/exp-relay.md
        - reference/libs/expansions/exp-ser.md
      - Standard Library:
        - reference/libs/stdlib/builtins.md
        - reference/libs/stdlib/threading.md
        - reference/libs/stdlib/struct.md
        - reference/libs/stdlib/gc.md
        - reference/libs/stdlib/timers.md
        - reference/libs/stdlib/watchdog.md
        - Time and Dates:
          - reference/libs/stdlib/time.md
          - reference/libs/stdlib/datetime.md
          - reference/libs/stdlib/suntime.md
        - Data Structures:
          - reference/libs/stdlib/fifo.md
          - reference/libs/stdlib/queue.md
        - Serialization:
          - reference/libs/stdlib/base64.md
          - reference/libs/stdlib/json.md
          - reference/libs/stdlib/cbor.md
        - Filesystem:
          - reference/libs/stdlib/fs.md
        - Peripherals:
          - reference/libs/stdlib/serial.md
          - reference/libs/stdlib/gpio.md
          - reference/libs/stdlib/i2c.md
          - reference/libs/stdlib/spi.md
          - reference/libs/stdlib/adc.md
          - reference/libs/stdlib/pwm.md
          - reference/libs/stdlib/can.md
          - reference/libs/stdlib/mcu.md
      - Networking:
        - reference/libs/networking/index.md
        - reference/libs/networking/net.md
        - reference/libs/networking/wifi.md
        - reference/libs/networking/eth.md
        - reference/libs/networking/socket.md
      - Protocols:
        - reference/libs/protocols/index.md
        - reference/libs/protocols/ntp.md
        - reference/libs/protocols/http.md
        - reference/libs/protocols/mqtt.md
        - reference/libs/protocols/modbus.md
      - Security and Cryptography:
        - reference/libs/crypto/index.md
        - reference/libs/crypto/element.md
      - Math:
        - reference/libs/math/math.md
        - reference/libs/math/bignum.md
      - zDeviceManager:
        - reference/libs/zerynth/zdm/index.md
        - reference/libs/zerynth/zdm/examples.md
      - Time Series Log:
        - reference/libs/zerynth/tslog/index.md
      - Sensors:
        - reference/libs/zerynth/zsensors/index.md
      - Components:
          - reference/libs/components/index.md
          - reference/libs/components/bme280/index.md
          - reference/libs/components/bmp180/index.md
          - reference/libs/components/bno055/index.md
      - Command Line Interface:
          - reference/cli/ztc/index.md
          - reference/cli/zdm/index.md
      - FAQ:
          - reference/faq/installer.md
          - reference/faq/vscode.md
          - reference/faq/filesystem.md
    - zCloud APIs:
      - reference/api/zdm/index.md
      - reference/api/zstorage/index.md
    - Changelog: reference/changelogs/index.md
    - What's new in Zerynth v3.x: reference/changelogs/whatsnew.md


- Demos:
  - Zerynth OS:
    - demos/zerynth-os/hello_zerynth.md
    - demos/zerynth-os/multi_serial.md
    - demos/zerynth-os/multi_thread_basic.md
    - demos/zerynth-os/c_language_interface.md
    - demos/zerynth-os/adc.md
    - demos/zerynth-os/i2c.md
    - demos/zerynth-os/spi.md
    - demos/zerynth-os/watchdog.md
    - demos/zerynth-os/zdm_simple.md
    - demos/zerynth-os/Easy_Keyboard_Module_with_Zerynth_and_Riverdi_IoT_Display.md
    - demos/zerynth-os/Combining_IoT_and_Blockchain_Using_Simple_Python.md
  - ZDM:
    - {Getting Started: /latest/deploy/getting_started_with_sdk/}
    - demos/zdm/Connect_Power_Bi_to_the_Zerynth_Device_Manager.md
    - demos/zdm/Connect_Zerynth_Device_Manager_with_Grafana_for_IoT_data_Visualization.md
  - 4ZeroBox:
    - demos/4zerobox/Hello_4ZeroBox.md
    - demos/4zerobox/Multi_Blinking.md
    - demos/4zerobox/Connecting_the_4Zerobox_to_Zerynth_Device_Manager_over_Ethernet.md
    - demos/4zerobox/Connecting_the_4ZeroBox_to_Zerynth_Device_Manager_over_WiFi.md
    - demos/4zerobox/Firmware_over_the_air_Updates_for_4ZeroBox_over_WiFi.md



plugins:
- search
- minify: {minify_html: true}
site_name: Zerynth Documentation
theme:
    custom_dir: material
    favicon: images/favicon.png
    features:
      - navigation.tabs
    font: {code: Roboto Mono, text: Roboto}
    logo: images/favicon-white.png
    name: material
    palette: {accent: red, primary: indigo}
google_analytics:
  - UA-64288331-2
  - auto
...
