backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "images" # Media files will be stored in the repo under images/uploads
public_folder: "images/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey
collections:
  - name: "New_Page" # Used in routes, e.g., /admin/collections/blog
    label: "New_Page" # Used in the UI
    folder: "docs/new_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Zerynth_in_a_nutshell"
        name: "Zerynth_in_a_nutshell"
        file: "docs/intro/index.md"
        preview_path: "docs/intro/index.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Getting_Started_DB_ZM1"
        name: "Getting_Started_DB_ZM1"
        file: "docs/gettingstarted/ZM1-DB.md"
        preview_path: "docs/gettingstarted/ZM1-DB.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Develop"
        name: "Develop"
        file: "docs/develop/index.md"
        preview_path: "docs/develop/index.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Deploy_and_Manage"
        name: "Deploy_and_Manage"
        file: "docs/deploy/index.md"
        preview_path: "docs/deploy/index.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Deploy_and_manage_SDK"
        name: "Deploy_and_Manage_sdk"
        file: "docs/deploy/getting_started_with_sdk.md"
        preview_path: "docs/deploy/getting_started_with_sdk.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Deploy_and_manage_RPI"
        name: "Deploy_and_Manage_rpi"
        file: "docs/deploy/getting_started_with_rpi.md"
        preview_path: "docs/deploy/getting_started_with_rpi.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Deploy_and_manage_web_interface"
        name: "Deploy_and_Manage_web_interface"
        file: "docs/deploy/web_interface.md"
        preview_path: "docs/deploy/web_interface.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Zerynth_Hardware_4ZB"
        name: "Zerynth_Hardware_4ZB"
        file: "docs/4zp/4ZeroBox.md"
        preview_path: "docs/4zp/4ZeroBox.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "ZDM_library_index"
        name: "ZDM_Index"
        file: "docs/reference/libs/zerynth/zdm/docs/index.md"
        preview_path: "docs/reference/libs/zerynth/zdm/docs/index.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "ZDM_library_GS"
        name: "ZDM_GS"
        file: "docs/reference/libs/zerynth/zdm/docs/zdm.md"
        preview_path: "docs/reference/libs/zerynth/zdm/docs/zdm.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "ZDM_library_EX"
        name: "ZDM_EX"
        file: "docs/reference/libs/zerynth/zdm/docs/examples.md"
        preview_path: "docs/reference/libs/zerynth/zdm/docs/examples.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
