---
markdown_extensions:
- meta
- admonition
- footnotes
- meta
-   codehilite: {guess_lang: false}
-   toc: {permalink: true}
-   pymdownx.betterem: {smart_enable: all}
- pymdownx.caret
- pymdownx.critic
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
-   pymdownx.tasklist: {custom_checkbox: true}
- pymdownx.tabbed
- pymdownx.tilde
nav: 
    - index.md
    - basics.md
    - seqmap.md
    - pinmap.md
    - clang.md
    - Zerynth OS:
        - zos.md
        - vm.md
        - vosal.md
        - vhal.md
plugins:
- search
-   minify: {minify_html: true}
- awesome-pages
site_name: Programming Guide
theme:
    font: {code: Roboto Mono, text: Roboto}
    name: material
    palette: {accent: red, primary: indigo}
...

